function Hd = filtreIIR_But
%FILTREIIR_BUT Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.12 and the Signal Processing Toolbox 6.15.
%
% Generated on: 10-Apr-2013 17:10:19
%

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in MHz.
Fs = 20;  % Sampling Frequency

Fpass = 6;           % Passband Frequency
Fstop = 7;           % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
Astop = 80;          % Stopband Attenuation (dB)
match = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
